---
- name: Execute echo command and display output
  hosts: TEST
  gather_facts: no
  tasks:
    - name: Execute echo command
      command:
        cmd: echo "Hello, this is a test message from Ansible."
      register: echo_output

    - name: Display echo output
      debug:
        msg: "{{ echo_output.stdout }}"
